<!-- Message de notification -->

<!-- Code HTML à écrire -->

<div class="guycontainer">


    <div class="flex">
        <article>
            <img class="imgguy" src="<?= $wwwUrl ?>/images/img/salledurestaurant.jpg">
            <p class="hidden">Le Restaurant</p>
        </article>
        <article>
        <img class="imgguy" src="<?= $wwwUrl ?>/images/img/RestaurantLeCamionquifumeSébastienChampeaux.jpg">
        <p class="hidden">L'Ambiance</p>
        </article>

        <article>

        <img class="imgguy" src="<?= $wwwUrl ?>/images/img/AVM79671.jpg" alt="#"><p class="hidden">Quartier</p>

        </article>
        <article>

        <img class="imgguy" src="<?= $wwwUrl ?>/images/img/img2338.jpg" alt="#"><p class="hidden">Sa Terrasse</p>

        </article>

        <article>

        <img class="imgguy" src="<?= $wwwUrl ?>/images/img/RestaurantCucinaByblosAmbianceHotelByblosSaintTropez.jpg"><p class="hidden">Une Cuisine</p>

        </article>
        <article>

            <img class="imgguy" src="<?= $wwwUrl ?>/images/img/RestaurantLeCamionquifumeSébastienChampeaux9.jpg">

            <p class="hidden">...un concept...</p>    

        </article>

        <article>

        <img class="imgguy" src="<?= $wwwUrl ?>/images/img/XVMdfa43516-c065-11e5-b21aaecb1c98c62d.jpg"><p class="hidden">...un concept...</p> 

        </article>

        <article>

        <img class="imgguy" src="<?= $wwwUrl ?>/images/img/vuemezzanine0.jpg"><p class="hidden">...un concept...</p> 

        </article>


        <article>

        <img class="imgguy" src="<?= $wwwUrl ?>/images/img/pitaya-bloc-photo-02-restaurantthailandais.jpg"><p class="hidden">...un concept...</p> 

        </article>


        <article>

        <img class="imgguy" src="<?= $wwwUrl ?>/images/img/tours1.jpg"><p class="hidden">...un concept...</p>

        </article>

​

    </div>

​

</div>